gems:		 [jekyll-sitemap]
zk:			 <a href="http://zoako.com">zoako</a>
bg:			 <a href="http://bitgym.com">bitgym</a>
ds:			 <a href="http://facebook.com/dicestorm">dicestorm</a>
twitter: 	 <a href="http://www.twitter.com/keerthiko">@keerthiko</a>
highlighter: pygments