baseURL = 'https://korc.me/'
languageCode = 'en-us'
title = 'kOrc'
theme = 'hugo-theme-nightfall'

[languages]
	[languages.en]
		title = "kOrc.me"
		subtitle = "trains. cities. games."
		[languages.en.params.logo]
			logoText = "korc.me"
			logoHomeLink = "/"
[menu]
  	[[menu.header]]
		name = "essays"
		weight = 1
		url = "essays"

readingTime = true
published = true
