baseURL = 'https://korc.me/'
languageCode = 'en-us'
title = 'kOrc'
theme = 'hugo-theme-nightfall'
ignorefiles = ["_notes/."]
[languages]
	[languages.en]
		title = "kOrc.me"
		[languages.en.params]
			subtitle = "trains. cities. games."
			[languages.en.params.logo]
				logoText = "korc.me"
				logoHomeLink = "/"
[menu]
  	[[menu.header]]
		name = "essays"
		weight = 1
		url = "essays"
  	[[menu.header]]
		name = "about"
		weight = 2
		url = "about"

[params]
	dicestorm = '[Operation Dicestorm](https://dicestormgame.com/)'
	hostname = 'kOrc.me'
	author = 'kOrc'
	custom_css = [
		"css/image-modal.css",
		"css/custom.css"
	]

readingTime = true
published = true
