baseURL = 'https://korc.me/'
languageCode = 'en-us'
title = 'kOrc'
theme = 'hugo-theme-nightfall'
ignorefiles = ["_notes/."]
[languages]
	[languages.en]
		title = "kOrc.me"
		[languages.en.params]
			subtitle = "trains. cities. games."
			[languages.en.params.logo]
				logoText = "korc.me"
				logoHomeLink = "/"
[menu]
  	[[menu.header]]
		name = "essays"
		weight = 1
		url = "essays"
  	[[menu.header]]
		name = "about"
		weight = 2
		url = "about"

[params]
	dicestorm = '[Operation Dicestorm](https://dicestormgame.com/)'
	hostname = 'kOrc.me'
	author = 'kOrc'
	custom_css = [
		"css/image-modal.css",
		"css/custom.css"
	]
	[[params.categorydata]]
	  	name = "play"
	    heading = "Play"
	    intro = "I talk a lot about game design, occasionally about other things game-related."
	[[params.categorydata]]
	  	name = "tech"
	    heading = "Tech/startups/product"
	    intro = "Product ideas, thoughts about running a business, technical nitty-gritty."
	[[params.categorydata]]
	  	name = "nomad"
	    heading = "Nomad chronicles"
	    intro = "I didn't think I'd write about this much. However, being a nomad became a significant part of my identity and [cities became my closest friends](/essays/1803_cities) so I talk about it now -- a lot."
	[[params.categorydata]]
	  	name = "learn"
	    heading = "Learning"
	    intro = "I think a lot about learning and education. Surprisingly often I'm torn between placing a post here or above in Play, because I talk about games + education a lot."
	[[params.categorydata]]
	  	name = "meta"
	    heading = "Meta: writing, life, the world"
	    intro = "My least incoherent thoughts about the all other things."

readingTime = true
published = true
