baseURL = 'https://korc.me/'
languageCode = 'en-us'
title = 'kOrc'
theme = 'hello-friend-ng'
[languages]
	[languages.en]
		title = "kOrc.me"
		subtitle = "trains. cities. games."
		[languages.en.params.logo]
			logoText = "korc.me"
			logoHomeLink = "/"
[[menu.main]]
    identifier = "essays"
    name       = "Essays"
    url        = "/essays"